### ISSUE TITLE
energy predictions | carnot

### ISSUE THREAD

**Issue by Symbiot78** [dykandDK/home-assistant-config#2]
hey

energy_predictions.yaml
I had to change the code to match langauge (I use english)

but more importantly the data generator didn't fit:

      var data = entity.attributes.prognose.map((start, index) => {
        return [new Date(start["date"]).getTime(), entity.attributes.prognose[index]["value"]/1000];

I had to change the above to

      var data = entity.attributes.predictions.map((start, index) => {
        return [new Date(start["dktime"]).getTime(), entity.attributes.predictions[index]["prediction"]/1000];

because the rest-sensor returns dktime, utctime as the time placeholder and predition holds the price.
my rest sensor looks like this:

`- platform: rest
    resource: https://whale-app-dquqw.ondigitalocean.app/openapi/get_predict
    name: elprognose_carnotdk
    scan_interval: 3600
    headers:
      Accept: application/json
      apikey: !secret carnotdk_token
      username: !secret carnotdk_username
    params:
      daysahead: 7
      energysource: spotprice
      region: dk1
    json_attributes:
      - predictions
    value_template: "{% if value_json is not none %}OK {{value_json.predictions[0].addedtime}}{% else %}Unavailable{% endif %}"
`

**Comment by Symbiot78** [comment]
this is mostly a FYI :)

**Comment by dykandDK** [comment]
> this is mostly a FYI :)

Thanks for the information @Symbiot78 :)

I actually use nodeRED to pull the data from the Carnot API and also use the "dktime" values. However, I change that to "date" in the data returned to align with data from other sources (e.g. Grønnere Elforbrug). 

I also change the "prediction" field to "value" for the same reason.

**Comment by dykandDK** [comment]
Closed

**Comment by dykandDK** [comment]
Closed
