### ISSUE TITLE
Ladning stopper ikke  

### ISSUE THREAD

**Issue by Hovsa477** [dykandDK/home-assistant-config#3]
Hejsa. 
Jeg oplever at opladningen ikke stopper som den skal. Automatisk opladning er aktiveret. 
Men jeg har flere gange oplevet at ladningen fortsætter, hvor forbruget er højere end produktionen. Håber du har en løsning i ærmet til denne

![inbound8026546032955747879](https://github.com/dykandDK/home-assistant-config/assets/171944281/4556eea0-f749-4616-80cd-98a45faa023b)

**Comment by dykandDK** [comment]
Koden stopper ikke selv opladningen, hvis der ikke produceres nok strøm for solceller. Det er et bevidst valg fra min side, da nogle biler måske vil have problemer med at starte opladningen igen.

Det er dog nemt selv at tilføje en automatisering, der stopper opladningen helt, hvis der ikke produceres nok strøm fra solen. Men man bør nok kigge på et gennemsnit over en længere periode for at sikre, at opladningen ikke hele tiden stoppes, når der går en sky for solen...

**Comment by dykandDK** [comment]
Lukkes
